name: Daily Trigger

on:
  schedule:
    - cron: '30 10 * * *'  # This is 10:30 AM UTC which corresponds to 4:00 PM IST

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Example step
        run: echo "This is a scheduled workflow run"
